# Generated by Django 3.0.3 on 2020-03-28 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('username', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('article', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论列表',
                'db_table': 'comment',
                'ordering': ['-date_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_time'], 'verbose_name': '博客', 'verbose_name_plural': '博客列表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_time'], 'verbose_name': '用户', 'verbose_name_plural': '用户列表'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='blog',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
